import { minutesText, rateText, trend, weekdays } from '../domain/report'
import { goalAward, goalRate, type CategorySummary, type Overview } from '../domain/sharing'

export function CategoryCards({ categories }: { categories: CategorySummary[] }) {
  return <section className="weekly-section"><header><h3>分类完成情况</h3><span>本周安排</span></header>{!categories.length && <p className="weekly-muted">暂无分类统计。</p>}<div className="report-categories">{categories.map((c, i) => <article key={i} style={{ borderTopColor: c.color }}><h4><i className="category-dot" style={{ background: c.color }}/>{c.name}</h4><dl><div><dt>习惯打卡</dt><dd>{rateText(c.counts.habitDone, c.counts.habitReviewed)}<small>{c.counts.habitDone}/{c.counts.habitReviewed} 次 · {c.counts.habitPending} 次待回顾</small></dd></div><div><dt>目标计划</dt><dd>{goalRate(c.counts) === null ? '—' : `${goalRate(c.counts)}%`} {goalAward(c.counts)}<small>必做 {c.counts.goalDone}/{c.counts.goalRequired} · 附加 {c.counts.goalOptionalDone}/{c.counts.goalOptional}</small></dd></div><div><dt>本周最长连续</dt><dd>{c.counts.habitBestStreak} 天</dd></div><div><dt>打卡中断</dt><dd>{c.counts.habitBreaks} 次</dd></div></dl></article>)}</div></section>
}
export default function ShareOverview({ report: r }: { report: Overview }) {
  const c = r.counts, previous = r.history.at(-1)?.counts
  const change = (current: number, prior?: number) => prior ? Math.round((current - prior) * 100 / prior) : null
  return <div className="weekly-page"><section className="weekly-hero"><small>{r.weekStart} — {r.weekEnd}</small><h3>一周小笺</h3><p>截至 {r.through}</p></section>
    <section className="weekly-numbers"><div><small>完成事项</small><strong>{c.completed}<i>/{c.planned}</i></strong><span>{trend(change(c.completed, previous?.completed))}</span></div><div><small>专注时间</small><strong>{minutesText(c.focusMinutes)}</strong><span>{trend(change(c.focusMinutes, previous?.focusMinutes))}</span></div><div><small>习惯打卡</small><strong>{rateText(c.habitDone, c.habitReviewed)}</strong><span>{c.habitPending} 次待回顾</span></div><div><small>目标计划</small><strong>{goalRate(c) === null ? '—' : `${goalRate(c)}%`}</strong><span>{goalAward(c)} · 必做 {c.goalDone}/{c.goalRequired} · 附加 {c.goalOptionalDone}/{c.goalOptional}</span></div></section>
    <section className="weekly-section"><header><h3>坚持的痕迹</h3></header><div className="habit-week-summary"><span>本周最长连续 <b>{c.habitBestStreak}</b> 天</span><span><b>{c.habitBreaks}</b> 次中断</span><span><b>{c.habitReviewed - c.habitDone}</b> 次未完成</span></div></section>
    <CategoryCards categories={r.categories}/>
    <section className="weekly-section"><header><h3>每天的完成情况</h3></header><div className="weekly-table-scroll"><table className="weekly-table"><thead><tr><th>日期</th><th>事项完成</th><th>专注</th><th>习惯</th><th>目标计划</th></tr></thead><tbody>{r.daily.map((d, i) => <tr key={d.date}><th>{d.date.slice(5)} 周{weekdays[i]}</th><td>{d.date <= r.through ? `${d.counts.completed}/${d.counts.planned}` : '—'}</td><td>{d.date <= r.through ? minutesText(d.counts.focusMinutes) : '—'}</td><td>{rateText(d.counts.habitDone, d.counts.habitReviewed)}</td><td>{goalRate(d.counts) === null ? '—' : `${goalRate(d.counts)}%`}</td></tr>)}</tbody></table></div></section>
    <section className="weekly-section"><header><h3>近四周对比</h3><span>与本周相同天数</span></header><table className="weekly-table"><thead><tr><th>周起始</th><th>完成率</th><th>专注</th><th>习惯</th><th>目标计划</th></tr></thead><tbody>{[...r.history, { date: r.weekStart, counts: c }].map(w => <tr key={w.date}><th>{w.date.slice(5)}{w.date === r.weekStart ? ' 本周' : ''}</th><td>{rateText(w.counts.completed, w.counts.planned)}</td><td>{minutesText(w.counts.focusMinutes)}</td><td>{rateText(w.counts.habitDone, w.counts.habitReviewed)}</td><td>{goalRate(w.counts) === null ? '—' : `${goalRate(w.counts)}%`}</td></tr>)}</tbody></table></section>
    {r.names.length > 0 && <section className="weekly-section"><header><h3>事项记录</h3></header>{r.names.map((n, i) => <div className="weekly-goal-row" key={i}><span>{n.kind} · {n.name}</span><strong>{n.done}/{n.total} · {rateText(n.done, n.total)}</strong></div>)}</section>}
    <blockquote><p>“{r.quote.text}”</p><footer>—— {r.quote.author} · {r.quote.source}</footer></blockquote>
  </div>
}
